.TH "DocumentationExamples/AppDelegate.m" 3 "Fri Sep 11 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DocumentationExamples/AppDelegate.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'AppDelegate\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
