.TH "DocumentationExamples/AppDelegate.h" 3 "Fri Sep 11 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DocumentationExamples/AppDelegate.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <UIKit/UIKit\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAppDelegate\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
