.TH "AppDelegate" 3 "Fri Sep 11 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AppDelegate \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIResponder, and <UIApplicationDelegate>\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "UIWindow * \fBwindow\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
