.TH "MathAPI" 3 "Fri Sep 11 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MathAPI \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits NSObject\&.
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(NSInteger) + \fBaddNumber:toNumber:\fP"
.br
.in -1c
.SH "Method Documentation"
.PP 
.SS "+ (NSInteger) addNumber: (NSInteger) firstNumber(NSInteger) secondNumber"
A really simple way to calculate the sum of two numbers\&.
.PP
\fBParameters:\fP
.RS 4
\fIfirstNumber\fP An NSInteger to be used in the summation of two numbers 
.br
\fIsecondNumber\fP The second half of the equation\&. 
.RE
.PP
\fBWarning:\fP
.RS 4
Please make note that this method is only good for adding non-negative numbers\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The sum of the two numbers passed in\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
