.TH "SmallCar" 3 "Fri Sep 11 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SmallCar \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCar\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "UIColor * \fBexteriorColor\fP"
.br
.ti -1c
.RI "NSString * \fBnickname\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\- (UIColor*) exteriorColor\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
sub class comment test 
.SS "\- (NSString*) nickname\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
sub class comment 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
