.TH "ViewController" 3 "Fri Sep 11 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIViewController\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(IBAction) \- \fBchangeCarType:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBCar\fP * \fBcar\fP"
.br
.ti -1c
.RI "NSString * \fBfunTitle\fP"
.br
.in -1c
.SH "Method Documentation"
.PP 
.SS "\- (IBAction) changeCarType: (UISegmentedControl*) segmentedControl"
Change user selection type
.PP
\fBParameters:\fP
.RS 4
\fIsegmentedControl\fP UISegmentedControl for change selection
.RE
.PP
Change user selection type
.PP
\fBParameters:\fP
.RS 4
\fIsegmentedControl\fP for change selection 
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\- (\fBCar\fP*) car\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
\fBViewController\fP class object for create new car 
.SS "\- (NSString*) funTitle\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [assign]\fP"
\fBViewController\fP class object for create car funTitle 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
