.TH "ViewController()" 3 "Fri Sep 11 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewController() \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "IBOutlet UITextField * \fBfirstNumberField\fP"
.br
.ti -1c
.RI "IBOutlet UITextField * \fBsecondNumberField\fP"
.br
.ti -1c
.RI "IBOutlet UILabel * \fBsumLabel\fP"
.br
.ti -1c
.RI "IBOutlet UILabel * \fBfunTitleLabel\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "\- (IBOutlet UITextField*) firstNumberField\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"
User First name 
.SS "\- (IBOutlet UILabel*) funTitleLabel\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"
User fun Title Label 
.SS "\- (IBOutlet UITextField*) secondNumberField\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"
User second Number Field 
.SS "\- (IBOutlet UILabel*) sumLabel\fC [read]\fP, \fC [write]\fP, \fC [nonatomic]\fP, \fC [weak]\fP"
User sum Label 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
