# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleDrove' do
    pod 'GoogleAPIClientForREST/Drive', '~> 1.2.1'
    pod 'Google/SignIn', '~> 3.0.3'
end
